name: Run TestInsight Agent

on:
  workflow_dispatch:  # Allows manual trigger
  workflow_run:
    workflows: ["Run Playwright Tests"]  # or your test workflow name
    types:
      - completed

jobs:
  run-agent:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run TestInsight Agent
        run: |
          python main.py
